[package]
name = "cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bitflags = "2.4.2"
once_cell = "1.19.0"
mappers = { path = "../mappers/" }
cartridge = { path = "../cartridge/" }
